export const mockStays = [
  {
    imageUrl: 'https://picsum.photos/id/10/300/300',
    details: 'Entire apartment',
    beds: '3',
    rating: '4.87',
    name: 'Cozy studio with balcony in Mitte',
    price: '$83',
  },
  {
    imageUrl: 'https://picsum.photos/id/101/300/300',
    details: 'Private room',
    beds: '1',
    rating: '4.23',
    name: 'Compact Queen Room',
    price: '$24',
  },
  {
    imageUrl: 'https://picsum.photos/id/1015/300/300',
    details: 'Entire apartment',
    beds: '2',
    rating: '4.91',
    name: 'Modern studio in the hearth of City',
    price: '$48',
  },
  {
    imageUrl: 'https://picsum.photos/id/1016/300/300',
    details: 'Entire apartment',
    beds: '5',
    rating: '4.55',
    name: 'Amazing view of the city',
    price: '$39',
  },
  {
    imageUrl: 'https://picsum.photos/id/1029/300/300',
    details: 'Entire apartment',
    beds: '1',
    rating: '4.19',
    name: 'Perfect resting stop',
    price: '$39',
  },
  {
    imageUrl: 'https://picsum.photos/id/1040/300/300',
    details: 'Private room',
    beds: '1',
    rating: '4.88',
    name: 'Castle Room',
    price: '$124',
  },
  {
    imageUrl: 'https://picsum.photos/id/10/300/300',
    details: 'Entire apartment',
    beds: '3',
    rating: '4.87',
    name: 'Cozy studio just step outside City Square',
    price: '$83',
  },
  {
    imageUrl: 'https://picsum.photos/id/101/300/300',
    details: 'Private room',
    beds: '1',
    rating: '4.23',
    name: 'Compact Queen Room',
    price: '$24',
  },
  {
    imageUrl: 'https://picsum.photos/id/1015/300/300',
    details: 'Entire apartment',
    beds: '2',
    rating: '4.91',
    name: 'Modern studio in the hearth of City',
    price: '$48',
  },
  {
    imageUrl: 'https://picsum.photos/id/1040/300/300',
    details: 'Private room',
    beds: '1',
    rating: '4.88',
    name: 'Castle Room',
    price: '$124',
  },
]